"""init growth_factors, users and likes tables

Revision ID: 43d41fcb1561
Revises: 
Create Date: 2026-09-20 23:24:19.090485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43d41fcb1561'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('growth_factors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('growth_factor_name', sa.String(length=100), nullable=False),
    sa.Column('growth_factor_description', sa.String(length=500), nullable=True),
    sa.Column('growth_factor_status', sa.String(length=20), nullable=False),
    sa.Column('image_key', sa.String(length=255), nullable=True),
    sa.Column('video_key', sa.String(length=255), nullable=True),
    sa.Column('growth_coefficient', sa.Float(), nullable=True),
    sa.Column('storage_impact_coefficient', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('creator_user_id', sa.Integer(), nullable=False),
    sa.Column('formed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_growth_factors_id'), 'growth_factors', ['id'], unique=False)
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('growth_factor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['growth_factor_id'], ['growth_factors.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_likes_id'), 'likes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_likes_id'), table_name='likes')
    op.drop_table('likes')
    op.drop_index(op.f('ix_growth_factors_id'), table_name='growth_factors')
    op.drop_table('growth_factors')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
